parameters:
    oro_search.string_filter.class: Oro\Bundle\SearchBundle\Datagrid\Filter\SearchStringFilter

services:
    oro_search.string_filter:
        class: %oro_search.string_filter.class%
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
        tags:
            - { name: oro_search.extension.search_filter.filter, type: string, datasource: search }

    oro_search.number_filter:
        class: 'Oro\Bundle\SearchBundle\Datagrid\Filter\SearchNumberFilter'
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
        tags:
            - { name: oro_search.extension.search_filter.filter, type: number, datasource: search }

    oro_search.number_range_filter:
        class: 'Oro\Bundle\SearchBundle\Datagrid\Filter\SearchNumberRangeFilter'
        arguments:
            - '@form.factory'
            - '@oro_filter.filter_utility'
        tags:
            - { name: oro_search.extension.search_filter.filter, type: number_range, datasource: search }
