security:
    firewalls:
        wsse_secured:
            pattern: ^/api/rest.*
            wsse:
                lifetime: 3600
                realm:    "Secured API"
                profile:  "UsernameToken"
            context: main
