entity_config:
    entity_config:
        entity:
            items:
                entity_name:
                    options:
                        priority: 200
                        indexed: true
                    grid:
                        type:               string
                        label:              oro.entity_config.entity_config.entity_name.label
                        filter_type:        string
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
                module_name:
                    options:
                        priority: 210
                        indexed: true
                    grid:
                        type:               string
                        label:              oro.entity_config.entity_config.module_name.label
                        filter_type:        choice
                        filter_options:
                            field_options:
                                multiple: true
                                choices: "@oro_entity_config.event_listener.entityconfig_grid_listener->getModuleChoices"
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
    attribute:
        entity:
            items:
                has_attributes:
                    options:
                        require_schema_update: false
                        value_type: boolean
                        default_value: false
        field:
            items:
                is_attribute:
                    options:
                        value_type: boolean
                        default_value: false
                        indexed: true
                    grid:
                        type: boolean
                        label: oro.entity_config.entity_config.attribute.field.items.is_attribute
                        renderable: false
                        is_visible: false
                        visible: false
                is_system:
                    options:
                        value_type: boolean
                        default_value: false
                        indexed: true
                searchable:
                    options:
                        value_type: boolean
                        default_value: false
                    form:
                        type: choice
                        options:
                            choices: ['No', 'Yes']
                            empty_value: false
                            block: other
                            subblock: frontend
                            label: oro.entity_config.entity_config.attribute.field.items.searchable
                filterable:
                    options:
                        value_type: boolean
                        default_value: false
                    form:
                        type: choice
                        options:
                            choices: ['No', 'Yes']
                            empty_value: false
                            block: other
                            subblock: frontend
                            label: oro.entity_config.entity_config.attribute.field.items.filterable
                sortable:
                    options:
                        value_type: boolean
                        default_value: false
                    form:
                        type: choice
                        options:
                            choices: ['No', 'Yes']
                            empty_value: false
                            block: other
                            subblock: frontend
                            label: oro.entity_config.entity_config.attribute.field.items.sortable
                enabled:
                    options:
                        value_type: boolean
                        default_value: false
                    form:
                        type: choice
                        options:
                            choices: ['No', 'Yes']
                            empty_value: false
                            block: other
                            subblock: frontend
                            label: oro.entity_config.entity_config.attribute.field.items.enabled
