services:
    oro_action.layout.block_type.action_line_buttons:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['action_line_buttons']]
            -
                - setOptionsConfig
                -
                    -
                        actions: {required: true}
                        entityId: {default: null}
                        entityClass: {default: null}
                        dialogRoute: ~
                        executionRoute: ~
        tags:
            - { name: layout.block_type, alias: action_line_buttons }

    oro_action.layout.block_type.action_combined_buttons:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['action_combined_buttons']]
            - [setParent, ['action_line_buttons']]
        tags:
            - { name: layout.block_type, alias: action_combined_buttons }

    oro_action.layout.block_type.line_buttons:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['line_buttons']]
            -
                - setOptionsConfig
                -
                    -
                        buttons: {required: true}
        tags:
            - { name: layout.block_type, alias: line_buttons }

    oro_action.layout.block_type.combined_buttons:
        parent: oro_layout.block_type.abstract_configurable
        calls:
            - [setName, ['combined_buttons']]
            - [setParent, ['line_buttons']]
        tags:
            - { name: layout.block_type, alias: combined_buttons }
