navigation:
    menu_config:
        items:
            oro_cron_schedule:
                label: 'oro.cron.menu.cron_schedule.label'
                route: 'oro_cron_schedule_index'
                extras:
                    position:    70
                    description: 'oro.cron.menu.cron_schedule.description'
                    routes:      ['oro_cron_schedule_index']

        tree:
            application_menu:
                children:
                    system_tab:
                        children:
                            oro_cron_schedule: ~

            shortcuts:
                children:
                    oro_cron_job_shortcut: ~

    titles:
        oro_cron_schedule_index: ~
